name: test


extraObjects: []

# extraObjects:
#   - apiVersion: batch/v1beta1
#     kind: CronJob
#     metadata:
#       name: "{{ .Values.name }}-somejob"
#     spec:
#       schedule: "*/10 * * * *"
#       concurrencyPolicy: Forbid
#       jobTemplate:
#         spec:
#           template:
#             spec:
#               containers:
#               - name: myjob
#                 image: ubuntu
#                 command:
#                 - echo
#                 args:
#                 - hello
#               restartPolicy: OnFailure
